name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  get_it: ^7.2.0
  injectable: ^2.1.0
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
dependencies:
  mockito: ^5.4.0
  injectable_generator:
