name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  domain:
    path: ../domain
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
